version: "3.8"
services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysqldb
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: admin0515

  api_service:
    container_name: parcial-arquisoft
    build: .
    restart: always
    ports:
      - 8089:8089
    networks:
      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/restaurant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0515
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - mysqldb
networks:
  springapimysql-net: